.TH "i3gocks" "1" 

.SH "NAME"
.PP
i3gocks - Minimal status line generator for i3/sway

.SH "SYNOPSIS"
.PP
i3gocks [-config]

.SH "OPTIONS"
.SS "-config path"
.PP
Specify path to config. (default: "$XDG_CONFIG_HOME/i3gocks/config.yml")

.SH "DESCRIPTION"
.PP
i3gocks is a minimal status line generator for i3bar/swaybar written in Go and configured in YAML.

.SH "CONFIGURATION"
.PP
For more info about the configuration please refer to the project website (\fIhttps://alexcoder04.github.io/i3gocks/\fP)

.SH "AUTHOR"
.PP
alexcoder04 <alexcoder04@protonmail.com>

